version: '3'

services:
  web:
    # image: php:apache
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "81:80"
    volumes:
      - ../:/var/www/html
      - ./000-default.conf:/etc/apache2/conf.d/000-default.conf
    depends_on:
      - db
  db:
    # image: mariadb
    build:
      context: ./
      dockerfile: Dockerfile.db
    environment:
      MARIADB_ROOT_PASSWORD: clonn
      MARIADB_DATABASE: test
      MARIADB_USER: clonn
      MARIADB_PASSWORD: clonn
    ports:
      - "3307:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d