version: '3'

services:
  web:
    # image: php:apache
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${port}:${port}"
      - "${port2}:${port2}"
    volumes:
      - ./:/var/www/html
      - ./000-default.conf:/etc/apache2/conf.d/000-default.conf
    depends_on:
      - db
  db:
    # image: mariadb
    build:
      context: ./
      dockerfile: Dockerfile.db
    environment:
      MARIADB_ROOT_PASSWORD: ${root_pswd}
      MARIADB_DATABASE: ${db_name}
      MARIADB_USER: ${username}
      MARIADB_PASSWORD: ${pswd}
    ports:
      - "${port_db}:${port_db2}"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    build:
      context: ./
      dockerfile: Dockerfile.phpmyadmin
    restart: always
    ports:
      - "${port_phpmyadmin}:${port_phpmyadmin}"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${root_pswd}